apiVersion: v1
kind: Service
metadata:
  name: {{ include "refly-web.fullname" . }}
  labels:
    {{- include "refly-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.podLabels.app | quote }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
