apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "refly-api.fullname" . }}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    {{- include "refly-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.podLabels.app | quote }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ .Values.podLabels.app | quote }}
        {{- include "refly-api.labels" . | nindent 8 }}
    spec:
      {{- with .Values.serviceAccount.name }}
      serviceAccountName: {{ . | quote }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "refly-api.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $p := .Values.containerPorts }}
            - containerPort: {{ $p }}
            {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            {{- with .Values.envFrom.configMapRef }}
            - configMapRef:
                name: {{ .name | quote }}
            {{- end }}
            {{- range $s := (.Values.envFrom.secretRefs | default (list)) }}
            - secretRef:
                name: {{ $s | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            {{- toYaml .Values.probes.startup.spec | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness.spec | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness.spec | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
